import { supabase } from '../lib/supabase'
import type { PaymentMethod, Discount, SalesOrder, SalesOrderItem, Payment, CartItem } from '../types/db'

export async function getPaymentMethods(businessId: string) {
  const { data, error } = await supabase
    .from('payment_methods')
    .select('*')
    .eq('business_id', businessId)
    .eq('is_active', true)
  if (error) throw error
  return data as PaymentMethod[]
}

export async function validateDiscount(businessId: string, code: string) {
  const now = new Date().toISOString()
  const { data, error } = await supabase
    .from('discounts')
    .select('*')
    .eq('business_id', businessId)
    .eq('code', code)
    .eq('is_active', true)
    .single()
  if (error) throw error
  const d = data as Discount

  // Client-side validation (RLS already filters business)
  if (d.valid_from && d.valid_from > now) throw new Error('Discount not yet active')
  if (d.valid_until && d.valid_until < now) throw new Error('Discount expired')
  if (d.usage_limit && d.usage_count >= d.usage_limit) throw new Error('Discount usage limit reached')
  return d
}

export async function getOrders(businessId: string, limit = 50) {
  const { data, error } = await supabase
    .from('sales_orders')
    .select('*, customer:customers(id, name, phone), items:sales_order_items(*, product:products(id, name))')
    .eq('business_id', businessId)
    .order('created_at', { ascending: false })
    .limit(limit)
  if (error) throw error
  return data as SalesOrder[]
}

export async function getPayments(businessId: string) {
  const { data, error } = await supabase
    .from('payments')
    .select('*, payment_method:payment_methods(id, name)')
    .eq('business_id', businessId)
    .order('created_at', { ascending: false })
  if (error) throw error
  return data as Payment[]
}

// ── Cart math helpers ──

function calcLineItem(item: CartItem) {
  const base = item.unitPrice * item.quantity
  const discounted = base * (1 - item.discountPercent / 100)
  const tax = +(discounted * item.taxRate / 100).toFixed(2)
  const total = +(discounted + tax).toFixed(2)
  return { base, discounted, tax, total }
}

export function calcCartTotals(items: CartItem[], discount: Discount | null) {
  let subtotal = 0
  let taxAmount = 0
  items.forEach((item) => {
    const line = calcLineItem(item)
    subtotal += line.discounted
    taxAmount += line.tax
  })
  subtotal = +subtotal.toFixed(2)
  taxAmount = +taxAmount.toFixed(2)

  let discountAmount = 0
  if (discount) {
    if (discount.type === 'percentage') {
      discountAmount = +(subtotal * discount.value / 100).toFixed(2)
      if (discount.max_discount_amount) {
        discountAmount = Math.min(discountAmount, discount.max_discount_amount)
      }
    } else if (discount.type === 'fixed_amount') {
      discountAmount = Math.min(discount.value, subtotal)
    }
  }

  const total = +(subtotal - discountAmount + taxAmount).toFixed(2)
  return { subtotal, discountAmount, taxAmount, total }
}

// ── Checkout ──

interface CheckoutPayload {
  businessId: string
  customerId: string | null
  discountId: string | null
  items: CartItem[]
  totals: ReturnType<typeof calcCartTotals>
  payments: { payment_method_id: string; amount: number }[]
  createdBy: string
}

export async function checkout(payload: CheckoutPayload): Promise<SalesOrder> {
  const { businessId, customerId, discountId, items, totals, payments, createdBy } = payload

  // 1. Create sales_order (order_number auto-generated by trigger)
  const { data: order, error: orderErr } = await supabase
    .from('sales_orders')
    .insert({
      business_id: businessId,
      customer_id: customerId,
      discount_id: discountId,
      order_number: '', // trigger generates
      status: 'completed',
      subtotal: totals.subtotal,
      discount_amount: totals.discountAmount,
      tax_amount: totals.taxAmount,
      total_amount: totals.total,
      created_by: createdBy,
    })
    .select()
    .single()
  if (orderErr) throw orderErr
  const salesOrder = order as SalesOrder

  // 2. Insert line items (prices snapshotted)
  const lineItems: Partial<SalesOrderItem>[] = items.map((item) => {
    const line = calcLineItem(item)
    return {
      order_id: salesOrder.id,
      product_id: item.product.id,
      variant_id: item.variant?.id ?? null,
      staff_id: item.staffId,
      quantity: item.quantity,
      unit_price: item.unitPrice,
      discount_percent: item.discountPercent,
      tax_rate: item.taxRate,
      tax_amount: line.tax,
      total_price: line.total,
    }
  })

  const { error: itemsErr } = await supabase
    .from('sales_order_items')
    .insert(lineItems)
  if (itemsErr) throw itemsErr

  // 3. Insert payments
  const paymentRows: Partial<Payment>[] = payments.map((p) => ({
    business_id: businessId,
    order_id: salesOrder.id,
    payment_method_id: p.payment_method_id,
    amount: p.amount,
    status: 'completed' as const,
    paid_at: new Date().toISOString(),
  }))

  const { error: payErr } = await supabase
    .from('payments')
    .insert(paymentRows)
  if (payErr) throw payErr

  return salesOrder
}
