-- ============================================================
-- MIGRATION 009 — Staff Commissions
-- Tables: staff_commissions, staff_commission_ledger
-- ============================================================

-- ============================================================
-- STAFF COMMISSIONS
-- Commission rate configuration per staff member.
-- product_id = NULL means the rule applies to ALL sales by
-- that staff member. Specific product rules take precedence.
-- ============================================================
create table public.staff_commissions (
  id               uuid          primary key default gen_random_uuid(),
  business_id      uuid          not null references public.businesses(id) on delete cascade,
  staff_id         uuid          not null references public.staff(id) on delete cascade,
  product_id       uuid          references public.products(id) on delete cascade,
  commission_type  text          not null default 'percentage'
                   check (commission_type in ('percentage','fixed_per_unit')),
  commission_value numeric(10,2) not null check (commission_value >= 0),
  is_active        boolean       not null default true,

  -- Prevent duplicate rules for same staff + product combination
  unique (staff_id, product_id)
);

comment on table  public.staff_commissions                   is 'Commission rate rules. product_id=NULL = catch-all for all products by this staff.';
comment on column public.staff_commissions.commission_type   is 'percentage = % of line total. fixed_per_unit = fixed ₹ per unit sold.';
comment on column public.staff_commissions.commission_value  is 'The % or ₹ amount. Applied by trigger on sales_order_items insert.';

-- ============================================================
-- STAFF COMMISSION LEDGER
-- One row per sales_order_item where a staff member earned
-- commission. Generated by a trigger — do not insert manually.
-- ============================================================
create table public.staff_commission_ledger (
  id            uuid          primary key default gen_random_uuid(),
  business_id   uuid          not null references public.businesses(id) on delete cascade,
  staff_id      uuid          not null references public.staff(id) on delete cascade,
  order_id      uuid          not null references public.sales_orders(id) on delete cascade,
  order_item_id uuid          not null references public.sales_order_items(id) on delete cascade,
  amount        numeric(10,2) not null check (amount >= 0),
  status        text          not null default 'pending'
                check (status in ('pending','paid')),
  paid_at       timestamptz,
  created_at    timestamptz   not null default now()
);

comment on table  public.staff_commission_ledger          is 'Immutable ledger of earned commissions per line item. Generated by trigger — do not insert manually.';
comment on column public.staff_commission_ledger.amount   is 'Commission amount computed from staff_commissions rule at time of sale.';
comment on column public.staff_commission_ledger.status   is 'pending = earned but not yet paid out. paid = disbursed to staff.';
comment on column public.staff_commission_ledger.paid_at  is 'Set when owner marks commission as paid to staff member.';