-- ============================================================
-- MIGRATION 006 — POS / Sales Orders
-- Tables: sales_orders, sales_order_items, discounts
-- Also: adds sales_order_id FK back to appointments
-- ============================================================

-- ============================================================
-- SALES ORDERS
-- Core billing document. Created from POS checkout or from a
-- completed appointment. Prices are captured at time of sale.
-- ============================================================
create table public.sales_orders (
  id              uuid          primary key default gen_random_uuid(),
  business_id     uuid          not null references public.businesses(id) on delete cascade,
  customer_id     uuid          references public.customers(id) on delete set null,
  appointment_id  uuid          references public.appointments(id) on delete set null,
  order_number    text          not null,
  status          text          not null default 'draft'
                  check (status in ('draft','confirmed','completed','cancelled','refunded')),
  subtotal        numeric(14,2) not null default 0 check (subtotal >= 0),
  discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
  tax_amount      numeric(12,2) not null default 0 check (tax_amount >= 0),
  round_off       numeric(5,2)  not null default 0,
  total_amount    numeric(14,2) not null default 0 check (total_amount >= 0),
  notes           text,
  created_by      uuid          references public.profiles(id) on delete set null,
  created_at      timestamptz   not null default now(),
  updated_at      timestamptz   not null default now(),

  unique (business_id, order_number)
);

comment on table  public.sales_orders                  is 'Core billing document — the invoice. Created from POS or on appointment completion.';
comment on column public.sales_orders.order_number     is 'Human-readable invoice number e.g. INV-0421. Auto-generated by application.';
comment on column public.sales_orders.customer_id      is 'NULL = anonymous walk-in. Link for loyalty and visit tracking.';
comment on column public.sales_orders.appointment_id   is 'NULL for direct POS sales. Set when invoice is generated from an appointment.';
comment on column public.sales_orders.discount_amount  is 'Total discount applied to the order (item-level + order-level combined).';
comment on column public.sales_orders.round_off        is 'Small rounding adjustment to arrive at a whole-number total if desired.';
comment on column public.sales_orders.subtotal         is 'Sum of all line item totals before discount and tax.';

-- ============================================================
-- SALES ORDER ITEMS
-- Line items in a sales order. All prices are captured at time
-- of sale — immune to future catalog price changes.
-- ============================================================
create table public.sales_order_items (
  id               uuid          primary key default gen_random_uuid(),
  order_id         uuid          not null references public.sales_orders(id) on delete cascade,
  product_id       uuid          not null references public.products(id) on delete restrict,
  variant_id       uuid          references public.product_variants(id) on delete restrict,
  staff_id         uuid          references public.staff(id) on delete set null,
  quantity         numeric(10,3) not null check (quantity > 0),
  unit_price       numeric(10,2) not null check (unit_price >= 0),
  discount_percent numeric(5,2)  not null default 0
                   check (discount_percent >= 0 and discount_percent <= 100),
  tax_rate         numeric(5,2)  not null default 0
                   check (tax_rate >= 0 and tax_rate <= 100),
  tax_amount       numeric(10,2) not null default 0 check (tax_amount >= 0),
  total_price      numeric(14,2) not null check (total_price >= 0)
);

comment on table  public.sales_order_items                  is 'Invoice line items. All monetary values snapshotted at time of sale.';
comment on column public.sales_order_items.staff_id         is 'Staff who performed the service — used for commission calculation.';
comment on column public.sales_order_items.unit_price       is 'Price per unit at time of sale. Not updated if catalog price later changes.';
comment on column public.sales_order_items.discount_percent is 'Item-level discount %. Applied before tax.';
comment on column public.sales_order_items.tax_amount       is 'Computed: (unit_price × qty × (1 - discount/100)) × tax_rate/100.';
comment on column public.sales_order_items.total_price      is 'Final line total: (unit_price × qty × (1 - discount/100)) + tax_amount.';

-- ============================================================
-- DISCOUNTS
-- Discount / coupon definitions. Applied at checkout.
-- usage_count is auto-incremented by trigger on application.
-- ============================================================
create table public.discounts (
  id                 uuid          primary key default gen_random_uuid(),
  business_id        uuid          not null references public.businesses(id) on delete cascade,
  name               text          not null,
  type               text          not null
                     check (type in ('percentage','fixed_amount','buy_x_get_y')),
  value              numeric(10,2) not null check (value >= 0),
  code               text,
  min_order_amount   numeric(10,2) not null default 0 check (min_order_amount >= 0),
  max_discount_amount numeric(10,2),
  is_active          boolean       not null default true,
  valid_from         timestamptz,
  valid_until        timestamptz,
  usage_limit        int           check (usage_limit > 0),
  usage_count        int           not null default 0 check (usage_count >= 0),
  created_at         timestamptz   not null default now(),

  unique (business_id, code)
);

comment on table  public.discounts                      is 'Coupon and discount rule definitions. Apply to sales_orders at checkout.';
comment on column public.discounts.type                 is 'percentage | fixed_amount | buy_x_get_y';
comment on column public.discounts.code                 is 'Coupon code for manual entry. NULL = auto-applied rule (e.g. loyalty tier).';
comment on column public.discounts.max_discount_amount  is 'Cap on the computed discount for percentage type. E.g. max 20% but no more than ₹200.';
comment on column public.discounts.usage_limit          is 'Maximum total uses. NULL = unlimited.';
comment on column public.discounts.usage_count          is 'Auto-incremented by application on each successful redemption.';

-- ============================================================
-- BACKFILL: Add sales_order_id to appointments
-- Deferred here to avoid forward-reference issues.
-- ============================================================
alter table public.appointments
  add column if not exists sales_order_id uuid
    references public.sales_orders(id) on delete set null;

comment on column public.appointments.sales_order_id is
  'Linked when appointment status → completed and the invoice is generated.';